version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: marmitexpress-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: marmitexpress-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/marmitexpress
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      CORS_ORIGIN_LOCAL: http://localhost:3000
      CORS_ORIGIN: https://marmit-express-opal.vercel.app/
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: marmitexpress-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: marmitexpress
    volumes:
      - db_data:/var/lib/postgresql/data
      
  adminer:
    image: adminer
    container_name: marmitexpress-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data: {}


